version: "2.4"
networks:
   etc_default:
     external: true

services:
  tpot2csv:
    container_name: tpot2csv
    image: tpot2csv
    restart: always
    read_only: true
    env_file: .env
    tmpfs:
      - /tmp
      - /var/tmp
      - /run
    ulimits:
      nofile:
        soft: 512
        hard: 1024
      nproc:
        soft: 8192
        hard: 8192
    pids_limit: 200
    cpu_shares: 512
    mem_limit: 1g

    build: .
    ports:
      - "65003:443"
    volumes:
      - "/data/nginx/cert/nginx.crt:/usr/local/apache2/conf/server.crt:ro"
      - "/data/nginx/cert/nginx.key:/usr/local/apache2/conf/server.key:ro"
      - "/data/tpot2csv/log:/usr/local/apache2/logs:rw"
      - "/data/tpot2csv/data:/usr/local/apache2/htdocs/data:rw"
    networks:
      - etc_default
    healthcheck:
      test: /usr/bin/pgrep -x httpd 2>/dev/null > /dev/null && /usr/bin/pgrep -x crond 2>/dev/null > /dev/null
      interval: 30s
      timeout: 5s
      start_period: 10s
      

      
      


